### ISSUE TITLE
site work's

### ISSUE THREAD

**Issue by troycla** [largefort/mrmine#1]
site work you just got to enable the cookie site will not work if you don't
![Screenshot 2024-04-08 3 34 41 PM](https://github.com/largefort/mrmine/assets/69062572/6d7016ac-ccf8-492f-a8a8-96fa6041faf6)

**Comment by largefort** [comment]
Hi troycla is it okay that you could have my permission to add one of my browser based games on admin x your new website to play iframe games so I grant you permission to put geotycoon aka oil Extraction Tycoon and medieval civilizations and if you agree with this permission so feel free to message me on github inbox and I will provide you with iframe code that contains the  game url so feel free to have one of my games on admin x I would be grateful

**Comment by troycla** [comment]
I am working on mrmine soon I will have it so the need for iframe are not of need once I am done I will add a mrmine game so other can take it if needed this is my senior year
